name: Run unitest on push and pull request

on:
  push:
  pull_request:

jobs:
  unitest:
    runs-on: ubuntu-latest
    steps:
    
    - name: NeuVector Vulnerability Scan Action
      uses: neuvector/scan-action@0.9.0

 
